#!/bin/sh

SCRIPT=$(readlink -f $0)
SCRIPTS_PATH=$(dirname $SCRIPT)

. $SCRIPTS_PATH/common.sh

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

if [ "$VERBOSE_BUILD" = "yes" ]; then
	CMAKE_VERBOSE_OPTION="-DCMAKE_VERBOSE_MAKEFILE=TRUE"
fi

if [ "$UNITY_BUILD" = "yes" ]; then
	CMAKE_UNITY_BUILD_OPTION="-DCMAKE_UNITY_BUILD=TRUE"
fi

if [ x"$BUILD_EXTRA_OPTIONS" != "x" ]; then
	CMAKE_EXTRA_OPTIONS="$BUILD_EXTRA_OPTIONS"
fi

cmake "$SOURCE_DIR" \
	-Wno-dev \
	-DSERVER_EXECUTABLE=${SERVER_EXECUTABLE} \
	-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
	$CMAKE_VERBOSE_OPTION \
	$CMAKE_UNITY_BUILD_OPTION \
	-DCMAKE_CXX_FLAGS=-rdynamic \
	$CMAKE_EXTRA_OPTIONS

cmake --build . --target install
