#!/bin/sh

SCRIPT=$(readlink -f $0)
SCRIPTS_PATH=$(dirname $SCRIPT)

. $SCRIPTS_PATH/common.sh

GEN_GAME_CFG="$INSTALL_DIR/$CONF-generated.cfg"
TS=$(date +"%Y-%m-%d-%T")

echo "# This cfg file generated by $SCRIPT" > $GEN_GAME_CFG
echo "exec $CONF.cfg" >> $GEN_GAME_CFG
echo "sv_name \"$SERVER_NAME\"" >> $GEN_GAME_CFG
echo "sv_port $SERVER_PORT" >> $GEN_GAME_CFG
if [ x"$SERVER_REGISTER" = "xyes" ]; then
    echo "sv_register 1" >> $GEN_GAME_CFG
elif [ x"$SERVER_REGISTER" = "xno" ]; then
    echo "sv_register 0" >> $GEN_GAME_CFG
fi

echo "sv_rcon_password $RCON_PASSWORD" >> $GEN_GAME_CFG
echo "ec_password $EC_PASSWORD" >> $GEN_GAME_CFG
echo "ec_port $EC_PORT" >> $GEN_GAME_CFG
echo "Logfile $LOG_DIR/$TS.log" >> $GEN_GAME_CFG
